### ISSUE TITLE
Click on CRXDeLite gives JS error

### ISSUE THREAD

**Issue by AxelHo** [nateyolles/aem-developer-chrome#19]
i use Chrome 44.0 and have the following JS error

extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: location.href.indexOf is not a function
    at normalizeLocation (chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/popup.js:704:23)
    at chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/popup.js:394:81
    at chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/background.js:16:9handler @ extensions::uncaught_exception_handler:8
2extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'replace' of undefined
    at te.k.url (chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/angular.min.js:39:359)
    at te.g [as $$checkUrlChange] (chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/angular.min.js:38:187)
    at k.$digest (chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/angular.min.js:109:88)
    at k.$apply (chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/angular.min.js:112:398)
    at chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/popup.js:399:22
    at chrome-extension://hgjhcngmldfpgpakbnffnbnmcmohfmfc/background.js:16:9

**Comment by nateyolles** [comment]
Issue found in Chrome dev channel. Closing ticket and will watch for issues as new browser versions are released.
